name: Discover Available WARP Endpoints

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 13 * * 1'

permissions:
  contents: write

jobs:
  discover-warp-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Download CloudflareWarpSpeedTest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/peanut996/CloudflareWarpSpeedTest/releases/latest --jq '.tag_name' |\
            xargs -I{} curl -sLk https://github.com/peanut996/CloudflareWarpSpeedTest/releases/download/{}/CloudflareWarpSpeedTest-{}-linux-amd64.tar.gz | tar -xzv

      - name: Run CloudflareWarpSpeedTest
        env:
          WARP_IP_RANGES: ${{ vars.WARP_IP_RANGES }}
        run: |
          ./CloudflareWarpSpeedTest -ip $(echo $WARP_IP_RANGES | tr ' ' ',') -all -n 500 -t 3

      - name: Store result.csv
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.csv
          if-no-files-found: error

      - name: Create README.md
        run: python create_readme.py

      - name: Commit and push README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update README with latest WARP endpoints" || echo "No changes to commit"
          git push